### ISSUE TITLE
Errors while running bb_segsort

### ISSUE THREAD

**Issue by fishmingyu** [vtsynergy/bb_segsort#5]
Hi, when I revise the code for n=400000, max_seg_sz=1000, your code has the following output.
[NOT PASSED] checking vals: #err = 34 (0.00% #nnz)
How could I get the right answer?

**Comment by fishmingyu** [comment]
In your README, you mentioned that:
"Equivalent elements are not guaranteed to keep the original relative order. We plan to provide a version to support stable sort in the future."
Can I interpret this as your code couldn't get the right output? Then how could I use your code as a building block for high-level applications without a guarantee of correctness?

**Comment by fishmingyu** [comment]
My testing environment:
CUDA 10.2 toolkit
Nvidia RTX 2080

**Comment by silkskier** [comment]
> In your README, you mentioned that:
> "Equivalent elements are not guaranteed to keep the original relative order. We plan to provide a version to support stable sort in the future."
> Can I interpret this as your code couldn't get the right output? Then how could I use your code as a building block for high-level applications without a guarantee of correctness?

I guess it's a little bit too late to reply, but if anyone was wandering what was wrong - this sorting algorithm is unstable (eg. doesn't preserve order of elements with equal values). If the array has 2 elements with exactly the same values there is ~ 50% chance, that they'll be swapped out.

It doesn't mean, that the algorithm failed to sort the array - it's still sorted, but with some equal values with changed order relatively to the oryginal array.

**Comment by fishmingyu** [comment]
I see, thank you for your reply!
